[turboMaCk]
name = "Marek Fajkus"
email = "marek.faj@gmail.com"

[Kubik161]
name = [ "Kubik161", "kubik" ]
email =  [ "30665071+Kubik161@users.noreply.github.com", "jakub.juroska161@gmail.com" ]

[wojciech29]
name = "wojciech29"
email = [ "wojciech29@users.noreply.github.com", "vojtech.remes@gmail.com" ]
