#! /usr/bin/env bash

set -xe

function print_legal() {
    pandoc -H latex/legal.sty --pdf-engine=xelatex -V block-headings $1 -t latex -s | sed '/\\def\\labelenumi/d' > out.tex
    xelatex out.tex
    mv -f out.pdf $2
    rm -f out*
}

print_legal content/statutes/index.en.md static/downloads/ictunion-statutes.pdf
print_legal content/statutes/index.cs.md static/downloads/ictunion-stanovy.pdf
print_legal content/statements/womens-day-2023.en.md static/downloads/womens-day-2023.pdf
print_legal content/statements/womens-day-2023.cs.md static/downloads/den-zen-2023.pdf
