name: "Build Website"

on:
  push:

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Verify formatting
        env:
          VERSION: 2.7.0
          OS: linux
          ARCH: amd64
        run: |
          curl -O -L -C - https://github.com/editorconfig-checker/editorconfig-checker/releases/download/$VERSION/ec-$OS-$ARCH.tar.gz
          tar xzf ec-$OS-$ARCH.tar.gz
          ./bin/ec-$OS-$ARCH

      # Nix
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Typecheck with tsc
        run: nix develop -c bash -c 'cd assets; npx tsc'

      - name: Run tests
        run: nix develop -c bash -c 'npm test'

      - name: Copile PDF with pandoc and xelatex
        run: nix develop -c bash -c './latex/print-all'

      - name: Build everything
        run: nix build

      - name: Run re-build script
        run: nix run . -- --buildDrafts --verbose
