name: "Build Docker / Codespaces container"

on:
  pull_request:
  push:

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . -t ict-web -f Dockerfile

      - name: Build web in docker image
        run: docker run --rm -v ${PWD}:/code -w /code -t ict-web /bin/bash -c 'npm install && hugo'
